---
abstract: 'Deal, score, and calculate expected win rates of poker hands. Base class for specific game types. '
author:
  - 'Nathaniel Graham <ngraham@cpan.org>'
requires:
  perl: '5.006'
  Algorithm::Combinatorics: '0'
  List::Util: '0'
  Moo: '0'
  Storable: '0'
  Test::More: '0'
  Tie::IxHash: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Poker-Eval
no_index:
  directory:
    - t
    - inc
version: '0.09'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
